### ISSUE TITLE
National glyphs support

### ISSUE THREAD

**Issue by jvymazal** [mo22/textstl#1]
Hi, unfortunately I do have about zero experience with JavaScript, so I am not sure whether to file issue here or in one of your dependencies, however at least in the [published version](http://www.mxs.de/textstl/)  it does not support national glyph (like čřžš) in any font while approx half of Google fonts does contain them.

Thanks for any help here.

**Comment by mo22** [comment]
Hi, unfortunately the bundler system I had used is not really working any more - I need to rework this to use webpack or something to even be able to test this :(

**Comment by jvymazal** [comment]
The rest of the system seems to work just fine, only when you use one of the special characters, it makes either a blank, square or similar (depending on the font) instead of it.

**Comment by mo22** [comment]
Hi, I found some time to re-write this to webpack + typescript and updating some dependencies.
Umlauts (öüä) seem to work fine, feel free to re-check your issue at https://www.mxs.de/textstl/

**Comment by jvymazal** [comment]
I think that umlauts and comma-versions (áíýé etc.) worked even before, problem is with the more-specific glyphs, such as ěščřžů, these are still ignored.

**Comment by mo22** [comment]
Those glyphs are not supported by those google fonts... I've updated the version so you can choose your own .ttf file (i.e. arial.ttf or anything) which includes these glyphs

**Comment by jvymazal** [comment]
Great, seems it is working alright. Many thanks!
